// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsixHelloWorld
{
    static class Vsix
    {
        public const string Id = "068b15b0-603b-4df4-9f43-5410274eab1c";
        public const string Name = "VsixHelloWorld";
        public const string Description = @"VsixHelloWorld";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "GregTrevellick";
        public const string Tags = "VsixHelloWorld";
    }
}
