// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsixHelloWorld
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCommand1PackageString = "24f06bc4-0d81-46a1-b2f2-bf2157c8406f";
        public const string guidCommand1PackageCmdSetString = "9ae25a2d-dc9c-4d97-b216-0ea6dc47c453";
        public const string guidImagesString = "4be5b583-95aa-4497-8cf0-0e8c50ba92fa";
        public static Guid guidCommand1Package = new Guid(guidCommand1PackageString);
        public static Guid guidCommand1PackageCmdSet = new Guid(guidCommand1PackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int Command1Id = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}
